version: '3.7'


x-backend-volumes: &backend-volumes
  volumes:
    - "./backend:${APP_DIR}"


services:
  
  nginx:
    ports:
      - "3000:80"
  
  backend:
    <<: *backend-volumes
    build:
      args:
        APP_STAGE: ${APP_STAGE}
  
  frontend:
    build:
      dockerfile: docker/local.dockerfile
    volumes:
      - "${APP_DIR}/node_modules"
      - "./frontend/src:${APP_DIR}"
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE_URL: "http://127.0.0.1:3000/api/"

  postgres:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
